backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "site/static/img"
public_folder: "img"

collections:
  - name: "guest-artist"
    label: "Guest Artist"
    folder: "site/content/guest-artist"
    create: true
    identifier_field: name
    fields:
      - {name: "name", label: "Name", widget: "string"}
      - {name: "headshot", label: "Headshot", widget: "image", required: false}
      - {name: "bio", label: "Bio", widget: "text"}
